/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/projetos'
    | '/sobre'
    | '/produtos/$slug'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/projetos'
    | '/sobre'
    | '/produtos/$slug'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/projetos'
    | '/sobre'
    | '/produtos/$slug'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ProjetosRoute: typeof ProjetosRoute
  SobreRoute: typeof SobreRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ProjetosRoute: ProjetosRoute,
  SobreRoute: SobreRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
